### ISSUE TITLE
Compile errors with Qt 5.5.1 and latest google breakpad

### ISSUE THREAD

**Issue by SevenBlocks** [JPNaude/dev_notes#2]
I followed the blog instructions exactly and ran into problems when I tried to compile on Ubuntu 14.04 using QT Creator 3.5.1 with QT 5.5.1 and gcc.
There were 20 errors total: 12 in crash_handler.cpp, 1 in exception_handler.cpp, 5 in minidump_writer.cc, and 2 in linux_ptrace_dumper.cc. 

There were some multiple definition errors like:
.../crashhandler/crash_handler.cpp:46: error: multiple definition of `Breakpad::CrashHandlerPrivate::pHandler' In function`QByteArray::length() const' in crash_handler.o

.../crashhandler/crash_handler.cpp:46: error: multiple definition of `Breakpad::CrashHandlerPrivate::bReportCrashesToSystem' in function`load<int>': in crash_handler.o

There were also several undefined reference errors in the google_breakpad code:
.../crashhandler/src/client/linux/minidump_writer/minidump_writer.cc:328: error: undefined reference to `google_breakpad::UContextReader::GetStackPointer(ucontext const*)'

Any idea what's causing the errors?

**Comment by SevenBlocks** [comment]
I figured it out. The multiple definition errors were because I had included crash_handler.cpp directly in the QT project. I removed it and those errors went away.
The undefined reference errors were because of some new files in the google breakpad project. Mostly in dump_writer_common. I added those to the .pri file and it compiled.
